"""Add phone_number field to Order model

Revision ID: 207df84b9b9b
Revises: 6547a797a606
Create Date: 2024-06-25 11:53:32.228516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207df84b9b9b'
down_revision = '6547a797a606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
