"""Add phone_number field to Order model

Revision ID: 6547a797a606
Revises: 0b225c79d47e
Create Date: 2024-06-24 23:38:03.842239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6547a797a606'
down_revision = '0b225c79d47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('credit_card_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.alter_column('cvv',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=4),
               existing_nullable=True)
        batch_op.alter_column('delivery_address',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('delivery_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('cvv',
               existing_type=sa.String(length=4),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
        batch_op.alter_column('credit_card_number',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
